on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Gitea Actions"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew shadowJar --no-daemon --stacktrace
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache
          ./gradlew shadowJar --no-daemon --stacktrace 
      - name: Find and Copy Jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -type f | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          cp "$JAR_FILE" ./VSit.jar
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: VSit_build
          path: VSit.jar
